"""Live OpenAI STT on audio generated by OpenAI TTS (self-contained, costs a little).

Run with:  RUN_LIVE_TESTS=1 pytest -m live tests/test_stt_live.py
"""

import os

import pytest
from openai import AsyncOpenAI

from app.config import get_settings
from app.models.kiosk import Language
from app.services.openai_stt_service import OpenAISpeechToText

pytestmark = [
    pytest.mark.live,
    pytest.mark.skipif(os.getenv("RUN_LIVE_TESTS") != "1", reason="set RUN_LIVE_TESTS=1"),
]


@pytest.mark.parametrize(
    ("language", "spoken", "expected"),
    [
        ("en-US", "Where can I find Colgate toothpaste?", "Colgate toothpaste"),
        ("my-MM", "Coca Cola ဘယ်မှာရှိလဲ", "ဘယ်မှာရှိလဲ"),
    ],
)
async def test_transcribes_generated_speech(language: Language, spoken: str, expected: str) -> None:
    settings = get_settings()
    if not settings.openai_api_key or not settings.openai_stt_model:
        pytest.skip("OPENAI_API_KEY / OPENAI_STT_MODEL not set")
    client = AsyncOpenAI(api_key=settings.openai_api_key.get_secret_value())
    try:
        speech = await client.audio.speech.create(
            model="gpt-4o-mini-tts", voice="ash", input=spoken, response_format="mp3"
        )
        stt = OpenAISpeechToText(client, model=settings.openai_stt_model, request_timeout=20)
        result = await stt.transcribe(
            speech.content,
            "audio.mp3",
            language,
            content_type="audio/mpeg",
            vocabulary=["Coca Cola", "Colgate"],
        )
    finally:
        await client.close()
    assert expected in result.text
    assert result.duration_ms > 0
